開発環境
fujiishun/fujii-training pull request #3
Opened 2022-12-08 01:16 UTC by fujiishun

開発環境の確認をお願いします。

2022-12-08 01:29 UTC, yupimaru requested changes
厳し目にコメントしました！！

2022-12-08 01:29 UTC, yupimaru commented on BE/RailsMySQL/Dockerfile
> +    yarn
```docker
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    nodejs \
    default-mysql-client \
    yarn
```

これ本当に必要ですか？

2022-12-08 01:29 UTC, yupimaru commented on BE/RailsMySQL/docker-compose.yml
> +        image: mysql:5.7
```
image: mysql:5.7
```

5.7にした理由を聞きたいです。

2022-12-08 01:29 UTC, yupimaru commented on FE/docker-react-app/Dockerfile
> +FROM node:18.12.1
```
FROM node:18.12.1
```

このバージョンにした理由を教えて下さい

2022-12-08 01:29 UTC, yupimaru commented on BE/RailsMySQL/Dockerfile
> +RUN bundle install
```
RUN bundle install
```

これだけだと、Rails立ち上がらなくないです？
毎回bashに入ってコマンド打つんですか？

2022-12-08 01:57 UTC, fujiishun commented on BE/RailsMySQL/docker-compose.yml
> +        image: mysql:5.7
学生時代に5.7を使用していたため8.0を存じておりませんでした。
8.0に変えたいと思います。

2022-12-08 01:58 UTC, fujiishun commented on FE/docker-react-app/Dockerfile
> +FROM node:18.12.1
これが最新Verだと認識しております。
最新ではなかったでしょうか？

2022-12-08 02:01 UTC, fujiishun commented on BE/RailsMySQL/Dockerfile
> +RUN bundle install
修正後再度連絡させてください。

2022-12-08 04:07 UTC, yupimaru commented on FE/docker-react-app/Dockerfile
> +FROM node:18.12.1
@fujiishun 
nodeのバージョン管理は僕がしているわけではないので、
最新バージョンを知りたければ調べましょう！

また、「最新を使え」ということを言いたいわけではないです。
シンプルにこのバージョンを選定した理由を教えて欲しいです！

2022-12-09 03:56 UTC, nishiodopeness commented on BE/RailsMySQL/Dockerfile
> +#RUN apt-get update && apt-get install -y \
こちらのコメントアウト不要であれば削除お願いします！

2022-12-09 04:50 UTC, nishiodopeness commented on BE/RailsMySQL/Dockerfile
> +#RUN apt-get update && apt-get install -y \
あd

2022-12-09 05:37 UTC, yupimaru approved these changes
いいんでない！

2022-12-09 05:52 UTC, fujiishun commented on BE/RailsMySQL/Dockerfile
> +#RUN apt-get update && apt-get install -y \
コメントアウト箇所削除いたしました。
また、環境構築に不要なファイルを削除いたしました。
コミット[delete non-development environment file]よりご確認ください。

2022-12-09 06:00 UTC, nishiodopeness commented
LGTMですー！

2022-12-09 06:01 UTC, nishiodopeness approved these changes

2022-12-09 06:29 UTC, nishiodopeness approved these changes

2022-12-09 07:52 UTC, merged