login機能実装いたしました
fujiishun/fujii-training pull request #4
Opened 2022-12-15 01:18 UTC by fujiishun

ログイン機能を実装いたしました。

サインイン時入力項目
・ID
・ニックネーム
・メールアドレス
・パスワード
・パスワード確認用

ログイン項目
・ID
・パスワード

ログイン保持期間
・2週間（ブラウザ落とすと再ログインが必要）

よろしくお願いいたします。

2022-12-15 03:36 UTC, Junyamenter commented
実際にログインする挙動のキャプチャとか添付できますか？？

2022-12-15 03:37 UTC, jun-yuaka commented
挙動見てみたいので、ログインする際のキャプチャとか添付できますか？？

2022-12-15 04:22 UTC, nishiodopeness commented
不要なファイル、console.logの記述は削除してください〜！

2022-12-15 05:41 UTC, fujiishun commented
<img width="1440" alt="スクリーンショット 2022-12-15 14 34 35" src="https://user-images.githubusercontent.co
<img width="1440" alt="スクリーンショット 2022-12-15 14 35 55" src="https://user-images.githubusercontent.com/119639849/207781246-a1f66af3-ff67-425b-90f8-13c375fde243.png">
m/119639849/207781140-a61fce5c-869c-4259-928f-f9e773dcf17e.png">
<img width="1440" alt="スクリーンショット 2022-12-15 14 36 09" src="https://user-images.githubusercontent
.com/119639849/207781257-c2afe939-c315-483c-8bec-9b2ecb464ab5.png">
<img width="1440" alt="スクリーンショット 2022-12-15 14 36 24" src="https://user-images.githubusercontent.com/119639849/207781274-e09dbcc4-6e2a-453f-84c5-1f7d1d1bbd19.png">
<img width="1440" alt="スクリーンショット 2022-12-15 14 36 50" src="https://user-images.githubusercontent.com/119639849/207781298-e67d4b6a-0693-4e44-a2c1-9dea937eb303.png">
<img width="1440" alt="スクリーンショット 2022-12-15 14 37 00" src="https://user-images.githubusercontent.com/119639849/207781402-dcd66c5d-f6ae-4576-8df5-6cf7282eef93.png">

2022-12-15 06:03 UTC, yupimaru requested changes
コメントしました！

2022-12-15 06:03 UTC, yupimaru commented on FE/docker-react-app/reactapp/src/interfaces/index.ts
> +  }
インデントがズレてると思うので修正しましょう！

2022-12-15 07:39 UTC, fujiishun commented on BE/RailsMySQL/app/controllers/api/v1/auth/sessions_controller.rb
> +//class Api::V1::Auth::SessionsController < ApplicationController
特に不具合がなかったため気が付きませんでした。
不要なクラスを削除しました。

2022-12-15 07:40 UTC, fujiishun commented on BE/RailsMySQL/app/controllers/api/v1/auth/sessions_controller.rb
> +      # render_error(404, I18n.t("devise_token_auth.sessions.user_not_found"))
不要ですね、すみません。削除いたします。

2022-12-15 07:40 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/App.tsx
> +<p>aaaa</p>
テスト用に入れたものが残っていました。削除いたしました。

2022-12-15 08:32 UTC, jun-yuaka commented on FE/docker-react-app/reactapp/src/App.tsx
> +      console.log(res)
このconsole.logはまだ使ってますか？
あと他にも結構console.logが残っているので、どうしても残したい場合は意図をコメントとして残してもらえるとわかりやすいかもです〜！
デバックの消し忘れかな？と思っちゃうので!

2022-12-15 08:43 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/App.tsx
> +      console.log(res)
ありがとうございます。
確かに他の方に共有する上で無駄な記載は省くべきですよね。
全て削除しておきたいと思います。

質問させてください。
console.logは全て削除するのが一般的なのでしょうか？
今後も度々使いそうだなと感じているlogは残していたのですが、、全削除の癖をつけるべきでしょうか？

2022-12-15 08:53 UTC, nishiodopeness commented on BE/RailsMySQL/config/routes.rb
> +  end
修正しました！


fix indent

2022-12-15 08:56 UTC, nishiodopeness reviewed
コメントしました！

2022-12-15 08:56 UTC, nishiodopeness commented on BE/RailsMySQL/app/controllers/api/v1/auth/sessions_controller.rb
> +  class Api::V1::Auth::SessionsController < ApplicationController
ここのインデント修正お願いします！

2022-12-15 08:56 UTC, nishiodopeness commented on BE/RailsMySQL/db/seeds.rb
> +end
こちらの削除お願いします！

2022-12-15 08:57 UTC, jun-yuaka commented on FE/docker-react-app/reactapp/src/App.tsx
> +      console.log(res)
> console.logは全て削除するのが一般的なのでしょうか？

一概にこうとは言い切れないのですが、基本的には残さないほうがよいと思います。
理由としては、完成しているはずの機能に不要にログを出力させる記述を残す必要はないと考えるからです。

2022-12-15 09:06 UTC, fujiishun commented on BE/RailsMySQL/app/controllers/api/v1/auth/registrations_controller.rb
> +    end
修正いたしました。https://github.com/fujiishun/fujii-training/pull/4/commits/1a725ed5534d812b179e0718b175237701c1a699

2022-12-15 09:06 UTC, fujiishun commented on BE/RailsMySQL/app/models/user.rb
> +authentication_keys: %i[email name]
修正いたしました。https://github.com/fujiishun/fujii-training/commit/1a725ed5534d812b179e0718b175237701c1a699

2022-12-15 09:06 UTC, fujiishun commented on BE/RailsMySQL/config/application.rb
> +config.api_only = true
修正いたしました。https://github.com/fujiishun/fujii-training/commit/1a725ed5534d812b179e0718b175237701c1a699

2022-12-15 09:07 UTC, fujiishun commented on BE/RailsMySQL/config/routes.rb
> +  end
修正いたしました。https://github.com/fujiishun/fujii-training/commit/1a725ed5534d812b179e0718b175237701c1a699

2022-12-15 09:07 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/interfaces/index.ts
> +  }
修正いたしました。https://github.com/fujiishun/fujii-training/commit/1a725ed5534d812b179e0718b175237701c1a699

2022-12-15 09:26 UTC, fujiishun commented on BE/RailsMySQL/app/controllers/api/v1/auth/sessions_controller.rb
> +  class Api::V1::Auth::SessionsController < ApplicationController
修正しました。https://github.com/fujiishun/fujii-training/pull/4/commits/bc1aa2ee08187ecde1dd1f8b20729c2c740145b2

2022-12-15 09:27 UTC, fujiishun commented on BE/RailsMySQL/db/seeds.rb
> +end
修正しました。https://github.com/fujiishun/fujii-training/pull/4/commits/bc1aa2ee08187ecde1dd1f8b20729c2c740145b2

2022-12-15 09:27 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/App.tsx
> +      console.log(res)
承知しました。
ご回答ありがとうございます。

今回は全て削除で対応いたしました。https://github.com/fujiishun/fujii-training/pull/4/commits/bc1aa2ee08187ecde1dd1f8b20729c2c740145b2

2022-12-15 23:55 UTC, jun-yuaka commented on FE/docker-react-app/reactapp/src/App.tsx
> +      console.log(res)
`console.log(res)`
このログ消してます??

あとはL40、L43あたりにも残っていそうですが、こちらは必要ですか??

2022-12-16 00:15 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/App.tsx
> +      console.log(res)
大変失礼いたしました。削除いたしました。https://github.com/fujiishun/fujii-training/pull/4/commits/2f128208f8c92d5eda5f998f313c4429f14c02f8

grepコマンド等によりしっかり確認を行うべきでした。以後気をつけます。

2022-12-16 00:29 UTC, yupimaru requested changes
コメントしました！

2022-12-16 00:29 UTC, yupimaru commented on BE/RailsMySQL/app/controllers/api/v1/auth/registrations_controller.rb
> + end
ここまだインデントおかしいかと！

2022-12-16 00:29 UTC, yupimaru commented on BE/RailsMySQL/app/controllers/api/v1/auth/sessions_controller.rb
> +end
endの数おかしくないですか？

2022-12-16 00:29 UTC, yupimaru commented on BE/RailsMySQL/config/application.rb
> +  config.api_only = true
ここまだインデントおかしいかと！

2022-12-16 00:29 UTC, yupimaru commented on BE/RailsMySQL/config/routes.rb
> +  end
ここまだインデントおかしいかと！

2022-12-16 00:29 UTC, yupimaru commented on FE/docker-react-app/reactapp/src/components/pages/Home.tsx
> +          <><h1>ログイン完了！！</h1>
好みの問題ですが、フラグメントの後ろは改行したほうがきれいかなと

2022-12-16 00:29 UTC, yupimaru commented on FE/docker-react-app/reactapp/src/components/pages/Home.tsx
> +            </div>
ここもインデント整えられそう

2022-12-16 00:29 UTC, yupimaru commented on FE/docker-react-app/reactapp/src/components/pages/SignIn.tsx
> +      //const strLength: undefined = (value as string).length;
このコメントアウトは必要ですか？

2022-12-16 00:29 UTC, yupimaru commented on FE/docker-react-app/reactapp/src/components/pages/SignOut.tsx
> +          <><h1>goodby</h1>
好みの問題ですが、フラグメントの後ろは改行したほうがきれいかなと

2022-12-16 00:29 UTC, yupimaru commented on FE/docker-react-app/reactapp/src/components/pages/TestPage.tsx
> +          <><h1>登録情報</h1>
好みの問題ですが、フラグメントの後ろは改行したほうがきれいかなと

2022-12-16 00:29 UTC, yupimaru commented on FE/docker-react-app/reactapp/src/components/pages/TestPage.tsx
> +
ここに空白行を開けてる意図はなんでしょ！

2022-12-16 00:29 UTC, yupimaru commented on FE/docker-react-app/reactapp/src/lib/api/auth.ts
> +  }
ここだけインデントおかしくないですか？

2022-12-16 00:52 UTC, fujiishun commented on BE/RailsMySQL/app/controllers/api/v1/auth/registrations_controller.rb
> + end
修正しました。https://github.com/fujiishun/fujii-training/pull/4/commits/86b7ef206e9ba91b3e4fb8a9df899d39d44f1103

2022-12-16 00:52 UTC, fujiishun commented on BE/RailsMySQL/app/controllers/api/v1/auth/sessions_controller.rb
> +end
endひとつ多かったですね。修正しました。https://github.com/fujiishun/fujii-training/pull/4/commits/86b7ef206e9ba91b3e4fb8a9df899d39d44f1103

2022-12-16 00:53 UTC, fujiishun commented on BE/RailsMySQL/config/application.rb
> +  config.api_only = true
修正しました。https://github.com/fujiishun/fujii-training/pull/4/commits/86b7ef206e9ba91b3e4fb8a9df899d39d44f1103

2022-12-16 00:53 UTC, fujiishun commented on BE/RailsMySQL/config/routes.rb
> +  end
修正しました。https://github.com/fujiishun/fujii-training/commit/86b7ef206e9ba91b3e4fb8a9df899d39d44f1103

2022-12-16 00:54 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/components/pages/Home.tsx
> +          <><h1>ログイン完了！！</h1>
ありがとうございます。改行の癖つけます。
修正しました。https://github.com/fujiishun/fujii-training/commit/86b7ef206e9ba91b3e4fb8a9df899d39d44f1103

2022-12-16 00:55 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/components/pages/SignIn.tsx
> +      //const strLength: undefined = (value as string).length;
エラー修正の際のメモが残っておりました。
もう不要なので削除いたしました。https://github.com/fujiishun/fujii-training/commit/86b7ef206e9ba91b3e4fb8a9df899d39d44f1103

2022-12-16 00:55 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/components/pages/SignOut.tsx
> +          <><h1>goodby</h1>
修正しました。https://github.com/fujiishun/fujii-training/commit/86b7ef206e9ba91b3e4fb8a9df899d39d44f1103

2022-12-16 00:56 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/components/pages/TestPage.tsx
> +
すみません意図はないです。
コード整理する癖をつけます。
修正しました。https://github.com/fujiishun/fujii-training/commit/86b7ef206e9ba91b3e4fb8a9df899d39d44f1103

2022-12-16 02:20 UTC, fujiishun commented on BE/RailsMySQL/app/controllers/api/v1/auth/registrations_controller.rb
> + end
修正しました。https://github.com/fujiishun/fujii-training/pull/4/commits/e6c0573c53f86c54c91636877d041a208ed67a4a

2022-12-16 02:22 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/lib/api/auth.ts
> +  }
修正しました。https://github.com/fujiishun/fujii-training/commit/e6c0573c53f86c54c91636877d041a208ed67a4a

2022-12-16 02:22 UTC, fujiishun commented on BE/RailsMySQL/config/routes.rb
> +  end
修正しました。https://github.com/fujiishun/fujii-training/commit/e6c0573c53f86c54c91636877d041a208ed67a4a

2022-12-16 02:24 UTC, fujiishun commented on BE/RailsMySQL/config/application.rb
> +  config.api_only = true
修正しました。https://github.com/fujiishun/fujii-training/commit/86b7ef206e9ba91b3e4fb8a9df899d39d44f1103

2022-12-16 02:26 UTC, jun-yuaka commented on FE/docker-react-app/reactapp/src/components/layouts/Header.tsx
> +      }
このelseも使ってないですかね??

2022-12-16 03:04 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/App.tsx
> +      }
ご自適ありがとうございます。修正しました。https://github.com/fujiishun/fujii-training/pull/4/commits/d327022686349c6ffa6d28a096c7b605b73a2360

2022-12-16 03:04 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/components/layouts/Header.tsx
> +      }
修正しました。https://github.com/fujiishun/fujii-training/commit/d327022686349c6ffa6d28a096c7b605b73a2360

2022-12-16 03:12 UTC, fujiishun reviewed
Meet時に口頭で指摘いただいた箇所の修正です。
その他の修正については完了次第報告します。

2022-12-16 03:12 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/components/pages/Home.tsx
> +              <h3><Link to="/testpage">登録情報</Link></h3>
@yupimaru インデント修正箇所です。

2022-12-16 03:12 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/components/pages/SignIn.tsx
>        }
@yupimaru 空白修正箇所です。

2022-12-16 03:12 UTC, fujiishun commented on FE/docker-react-app/reactapp/src/components/pages/SignUp.tsx
>        } else {
@yupimaru 空白修正箇所です。

2022-12-16 03:58 UTC, fujiishun commented
@yupimaru 
コードを整理しました。お手数ですがご確認お願い致します。
https://github.com/fujiishun/fujii-training/pull/4/commits/e6c0573c53f86c54c91636877d041a208ed67a4a　https://github.com/fujiishun/fujii-training/pull/4/commits/a784e6f09a60d7f83e18d7981185c941db7921bf

2022-12-16 04:05 UTC, yupimaru approved these changes

2022-12-16 05:05 UTC, fujiishun commented
@nishiodopeness 
prettier導入、動作確認完了しました。
インストール先を間違えたためコミットが汚くなっています。
申し訳ありません。
https://github.com/fujiishun/fujii-training/pull/4/commits/b6b030031e5bcd83966a08975277d48aa830419c
https://github.com/fujiishun/fujii-training/pull/4/commits/8f337bfa600b7e434382a4e7ba12ddc4ded073d4

2022-12-16 05:22 UTC, nishiodopeness approved these changes

2022-12-16 05:24 UTC, jun-yuaka approved these changes

2022-12-16 05:26 UTC, merged